#!/usr/bin/env perl

use strict;
use warnings;
use Text::Table::HTML;

print Text::Table::HTML::table(
    rows => [
        [0],
        [""],
        [undef],
        ["0"],
        ["0.0"],
        [1],
    ],
    header_row => 1,
);
